ASP.NET_Core_MVC_Practical/Models/Director.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace ASP.NET_Core_MVC_Practical.Models;

public partial class Director
{
    public int DirectorId { get; set; }

    [DisplayName("Director Name")]
    public string DirectorName { get; set; } = null!;

    public string Country { get; set; } = null!;

    public virtual ICollection<Movie> Movies { get; set; } = new List<Movie>();
}

ASP.NET_Core_MVC_Practical/Models/ErrorViewModel.cs
namespace ASP.NET_Core_MVC_Practical.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ASP.NET_Core_MVC_Practical/Models/Genre.cs
using System;
using System.Collections.Generic;

namespace ASP.NET_Core_MVC_Practical.Models;

public partial class Genre
{
    public int GenreId { get; set; }

    public string GenreName { get; set; } = null!;

    public virtual ICollection<Movie> Movies { get; set; } = new List<Movie>();
}

ASP.NET_Core_MVC_Practical/Models/Movie.cs
using System;
using System.Collections.Generic;

namespace ASP.NET_Core_MVC_Practical.Models;

public partial class Movie
{
    public int MovieId { get; set; }

    public string Title { get; set; } = null!;

    public int? ReleaseYear { get; set; }

    public decimal? Rating { get; set; }

    public int? DirectorId { get; set; }

    public int? GenreId { get; set; }

    public virtual Director? Director { get; set; }

    public virtual Genre? Genre { get; set; }
}

ASP.NET_Core_MVC_Practical/Models/MovieContext.cs
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace ASP.NET_Core_MVC_Practical.Models;

public partial class MovieContext : DbContext
{
    public MovieContext()
    {
    }

    public MovieContext(DbContextOptions<MovieContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Director> Directors { get; set; }

    public virtual DbSet<Genre> Genres { get; set; }

    public virtual DbSet<Movie> Movies { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        //if (!optionsBuilder.IsConfigured)
        //{
        //    optionsBuilder.UseSqlServer("Data Source=.;Initial Catalog=Movie;Integrated Security=True;Trust Server Certificate=True;");
        //}

        if (!optionsBuilder.IsConfigured)
        {
            optionsBuilder.UseSqlServer("Data Source=DESKTOP-C97SHFV;Initial Catalog=Movie;Integrated Security=True;Encrypt=True;Trust Server Certificate=True");
        }
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Director>(entity =>
        {
            entity.HasKey(e => e.DirectorId).HasName("PK__Director__26C69E46B3357A6F");

            entity.Property(e => e.Country).HasMaxLength(100);
            entity.Property(e => e.DirectorName).HasMaxLength(100);
        });

        modelBuilder.Entity<Genre>(entity =>
        {
            entity.HasKey(e => e.GenreId).HasName("PK__Genres__0385057E0EEB2CF1");

            entity.Property(e => e.GenreName).HasMaxLength(50);
        });

        modelBuilder.Entity<Movie>(entity =>
        {
            entity.HasKey(e => e.MovieId).HasName("PK__Movies__4BD2941A50544FC7");

            entity.Property(e => e.Rating).HasColumnType("decimal(2, 1)");
            entity.Property(e => e.Title).HasMaxLength(200);

            entity.HasOne(d => d.Director).WithMany(p => p.Movies)
                .HasForeignKey(d => d.DirectorId)
                .HasConstraintName("FK_Director");

            entity.HasOne(d => d.Genre).WithMany(p => p.Movies)
                .HasForeignKey(d => d.GenreId)
                .HasConstraintName("FK_Genre");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}

ASP.NET_Core_MVC_Practical/Controllers/DirectorsController.cs
using ASP.NET_Core_MVC_Practical.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace ASP.NET_Core_MVC_Practical.Controllers
{
    public class DirectorsController : Controller
    {
        private readonly MovieContext _movieContext;

        public DirectorsController(MovieContext movieContext)
        {
            _movieContext = movieContext;
        }

        [HttpGet]
        public IActionResult Index()
        {
            //DirectorModel Dirmodel = new DirectorModel();
            //Dirmodel.CountryList = new List<SelectListItem>();
            //var data = _movieContext.Directors.ToList();

            //Dirmodel.CountryList.Add(new SelectListItem
            //{
            //    Text = "Select Country",
            //    Value = ""
            //});
            //foreach (var item in data)
            //{
            //    Dirmodel.CountryList.Add(new SelectListItem
            //    {
            //        Text = item.Country,
            //        Value = item.DirectorId.ToString()
            //    });
            //    Dirmo
            //}

            //List<Director> directors = new List<Director>();
            //var allData = _movieContext.Directors.ToList();
            //directors = allData;

            //DirectorViewModel dvm = new DirectorViewModel()
            //{
            //    DiractorsList = directors,
            //    Counties = 
            //};

            var dirList = _movieContext.Directors.ToList();

            return View(dirList);
        }

        [HttpPost]
        public IActionResult Index(string search)
        {

            var searchDirectors = _movieContext.Directors.Where(s => s.DirectorName.Contains(search) || s.Country.Contains(search)).ToList();
            if (searchDirectors != null && search != null)
            {
                return View(searchDirectors);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }
    }
}

ASP.NET_Core_MVC_Practical/Controllers/GenresController.cs
using ASP.NET_Core_MVC_Practical.Models;

using Microsoft.AspNetCore.Mvc;

namespace ASP.NET_Core_MVC_Practical.Controllers
{
    public class GenresController : Controller
    {
        private readonly MovieContext _movieContext;

        public GenresController(MovieContext movieContext)
        {
            _movieContext = movieContext;
        }


        public IActionResult Index()
        {
            var genreList = _movieContext.Genres.ToList();
            return View(genreList);
        }
    }
}

ASP.NET_Core_MVC_Practical/Controllers/MoviesController.cs
using ASP.NET_Core_MVC_Practical.Models;

using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

using System.Linq;

namespace ASP.NET_Core_MVC_Practical.Controllers
{
    public class MoviesController : Controller
    {
        private readonly MovieContext _movieContext;
        public MoviesController(MovieContext movieContext)
        {
            _movieContext = movieContext;
        }

        public IActionResult Index(int? pageno)
        {
            if(pageno.HasValue)
            {
                int pageNo = (int) pageno;
                if (pageNo < 1)
                {
                    pageNo = 1;

                }
                var movieList = _movieContext.Movies.Include(g => g.Genre).Include(d => d.Director).Skip((pageNo - 1) * 3).Take(3).ToList();
                return View(movieList);
            }
            else
            {
                var movieList = _movieContext.Movies.Include(g => g.Genre).Include(d => d.Director).Take(3).ToList();
                return View(movieList);

            }
          
        }

        [HttpPost]
        public IActionResult Index(string search)
        {
            var seaechMovieList = _movieContext.Movies.Include(g => g.Genre).Include(d => d.Director).Where(s => s.Title.Contains(search) || s.Genre.GenreName.Contains(search) || s.Director.DirectorName.Contains(search) || s.Director.Country.Contains(search)).ToList();
            if (seaechMovieList != null && search != null)
            {
                return View(seaechMovieList);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }
    }
}

ASP.NET_Core_MVC_Practical/Views/Directors/Index.cshtml
@model IEnumerable<ASP.NET_Core_MVC_Practical.Models.Director>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

@* <p>
    <a asp-action="Create">Create New</a>
</p> *@

<form asp-controller="Movies" asp-action="Index" method="post" class="form-inline my-2 my-lg-0">
    <div class="row">
        <div class="col-6 d-flex">
            <input class="form-control mr-sm-2" type="search" name="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0 m-2" type="submit">Search</button>
        </div>
    </div>
</form>
<table class="table table-bordered table-striped mt-2">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DirectorName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Country)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DirectorName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country)
            </td>
        @*     <td>
                <a asp-action="Edit" asp-route-id="@item.DirectorId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.DirectorId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.DirectorId">Delete</a>
            </td> *@
        </tr>
}
    </tbody>
</table>

ASP.NET_Core_MVC_Practical/Views/Directors/Index1.cshtml
@model ASP.NET_Core_MVC_Practical.Models.Director

@{
    ViewData["Title"] = "Index";
}

<h1>Directors List</h1>

@* <p>
    <a asp-action="Create">Create New</a>
</p> *@
<form asp-controller="Directors" asp-action="Index" method="post" class="form-inline my-2 my-lg-0">
    <div class="row">
        <div class="col-6 d-flex">
    <input class="form-control mr-sm-2" type="search" name="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0 m-2" type="submit">Search</button>
        </div>
    </div>
</form>
@* <table class="table table-bordered table-striped mt-2">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.DirectorName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Country)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.DirectorName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.DirectorId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.DirectorId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.DirectorId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table> *@
<nav aria-label="Page navigation example">
    <ul class="pagination">
        <li class="page-item"><a class="page-link" href="#">Previous</a></li>
        <li class="page-item"><a class="page-link" href="#">1</a></li>
        <li class="page-item"><a class="page-link" href="#">2</a></li>
        <li class="page-item"><a class="page-link" href="#">3</a></li>
        <li class="page-item"><a class="page-link" href="#">Next</a></li>
    </ul>
</nav>

ASP.NET_Core_MVC_Practical/Views/Genres/Index.cshtml
@model IEnumerable<ASP.NET_Core_MVC_Practical.Models.Genre>

@{
    ViewData["Title"] = "Index";
}

<h1>Genre List</h1>
<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.GenreName)
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.GenreName)
            </td>
        </tr>
}
    </tbody>
</table>

ASP.NET_Core_MVC_Practical/Views/Movies/Index.cshtml
@model IEnumerable<ASP.NET_Core_MVC_Practical.Models.Movie>

@{
    ViewData["Title"] = "Movies List";
}

<h1>Movies List</h1>

<form asp-controller="Movies" asp-action="Index" method="post" class="form-inline my-2 my-lg-0">
    <div class="row">
        <div class="col-6 d-flex">
            <input class="form-control mr-sm-2" type="search" name="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0 m-2" type="submit">Search</button>
        </div>
    </div>
</form>

<table class="table table-bordered table-striped mt-2">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReleaseYear)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Rating)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Director)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genre)
            </th>
           
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReleaseYear)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rating)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Director.DirectorName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genre.GenreName)
            </td>
        </tr>
}

    </tbody>
</table>

<partial name="_Pagination"/>

ASP.NET_Core_MVC_Practical/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASP.NET_Core_MVC_Practical</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASP.NET_Core_MVC_Practical.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Movies" asp-action="Index"><img class="img-rounded" height="60" width="100" src="~/img/movie-logo.png" alt="Movie Logo" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Directors" asp-action="Index">Directors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Genres" asp-action="Index">Genres</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-controller="Movies" asp-action="Index">Movies</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
     @RenderBody()
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ASP.NET_Core_MVC_Practical - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ASP.NET_Core_MVC_Practical/Views/Shared/_Pagination.cshtml
@{
    ASP.NET_Core_MVC_Practical.Models.MovieContext context = new ASP.NET_Core_MVC_Practical.Models.MovieContext();
    int count =  context.Movies.Count();
    int pagenums = (int)Math.Ceiling(count / (double)3);
    string activeLink = "active";
}
<nav aria-label="Page navigation example">
    <ul class="pagination">
        
        @for (int i = 1; i <= pagenums; i++)
        {
            
            
        <li class="page-item p-1"><a class="page-link @activeLink" asp-action="Index" asp-controller="Movies" asp-route-pageno="@i">@i</a></li>  
        }
    </ul>
</nav>